#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Gude EMC3011 Time Source
# 23.06.2014 by Roland Mueller
#

def inventory_gude_emc3011_source(info):
    #debug
    #import pprint ; pprint.pprint(info)
    #return []
    inventory = []
    for state in info:
        inventory.append((None, state))
    return inventory


def check_gude_emc3011_source(item, params, info):
    for state in info:
        if state[0] == "1":
            return (0, "OK - Time Source is DCF77")
        elif state[0] == "0":
            return (1, "WARNING - Time Source is Quarz")
    return (3, "UNKNOWN - No Information about Time Source")

check_info['gude_emc3011_source'] = {
    'check_function': check_gude_emc3011_source,
    'service_description': "Time Source",
    'inventory_function': inventory_gude_emc3011_source,
    'has_perfdata': False,
}

snmp_info['gude_emc3011_source']  = ( ".1.3.6.1.4.1.28507.3.1", ['5'] )

snmp_scan_functions['gude_emc3011_source'] = lambda oid: "EMC Professional NET".lower() in oid(".1.3.6.1.2.1.1.1.0").lower()
