#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# NetGear ReadyData FAN Check
# 27.03.2014 by Roland Mueller
#

def inventory_netgear_readydata_fan(info):
    #debug
    #import pprint ; pprint.pprint(info)
    #return []
    inventory = []
    for number, speed, state, desc in info:
        if state == "ok":
            inventory.append((number, None))
    return inventory


def check_netgear_readydata_fan(item, params, info):
    for number, speed, state, desc in info:
        perfdata = [("rpm", speed)]
        if number == item:
            if state == "ok":
                return (0, "OK - "+desc+" is " + state + " at "+speed+"rpm", perfdata)
            else:
                return (2, "CRITICAL - "+desc+" is " + state + " at "+speed+"rpm", perfdata)
    return (3, "UNKNOWN - FAN not found")

check_info['netgear_readydata_fan'] = {
    'check_function': check_netgear_readydata_fan,
    'service_description': "FAN %s",
    'inventory_function': inventory_netgear_readydata_fan,
    'has_perfdata': True,
}

snmp_info['netgear_readydata_fan']  = ( ".1.3.6.1.4.1.4526.22.4.1", [ '1', '2', '3', '4' ] )

snmp_scan_functions['netgear_readydata_fan'] = lambda oid: "ReadyDATA OS".lower() in oid(".1.3.6.1.2.1.1.1.0").lower()
